### ISSUE TITLE
Issue: food regeneration disable code does no work properly

### ISSUE THREAD

**Issue by JR1811** [4ceRT4in/TitanReborn#21]
players should still be able to regenerate hearts by having full hunger bars
only when 1,5 hungers bars are lost the player does not regenerate (like the system in minecraft 1.8 and below)

**Comment by JR1811** [comment]
As far as I know, this system hasn't changed much. Starting with 3 Hunger points (1,5 icons) missing, the player won't regenerate health anymore. Only minor tweaks to how fast you will regenerate have been made depending on how much is missing.

Vanilla also has a Gamerule to disable regen with food, called `NATURAL_REGENERATION`.

What specifically needs to be changed here?

**Comment by 4ceRT4in** [comment]
private static int MIN_HUNGER = 16;
    private static int REGEN_TIME = 80;
    private static float EXHAUSTION = 6.0F;

    @SubscribeEvent
    public void tickPlayer(TickEvent.PlayerTickEvent event) {
        if (event.phase == TickEvent.Phase.START && event.player
                .getHealth() < event.player.getMaxHealth() && event.player
                .getFoodStats().getFoodLevel() >= MIN_HUNGER &&
                event.player.getEntityWorld().getWorldTime() % REGEN_TIME == 0L) {
            event.player.heal(1.0F);
            event.player.getFoodStats().addExhaustion(EXHAUSTION);
        }
    }

    @SubscribeEvent
    public void event(WorldEvent.Load event) {
        event.getWorld().getGameRules().setOrCreateGameRule("naturalRegeneration", "false");
    }
